name: Brian Lundin
description: "Articles on code, tech, design and creativity from Brian Lundin"
url: "http://code.brianlundin.com"

markdown: redcarpet
highlighter: pygments

sass:
  sass_dir: scss
  style: compressed
exclude: ["*.sublime-*"]

paginate: 5
paginate_path: "page:num"
permalink: /blog/:title.html
