name: Brian Lundin
description: "Articles on code, tech, design and creativity from Brian Lundin"

url: "http://code.brianlundin.com"
cdn: "http://cdn.code.brianlundin.com"

markdown: kramdown
highlighter: pygments

sass:
  sass_dir: _sass
  style: compressed

paginate: 5
paginate_path: "page:num"
permalink: blog/:title.html

exclude: ["node_modules",
          "Gruntfile.js",
          "bower.json",
          "package.json",
          "publish.sh",
          "README.md",
          "*.sublime-*"]
